# Generated by Django 6.0.3 on 2026-04-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(default='Unknown', max_length=64, unique=True)),
                ('episode_nb', models.IntegerField(primary_key=True, serialize=False)),
                ('opening_crawl', models.TextField(blank=True, null=True)),
                ('director', models.CharField(default='Unknown', max_length=32)),
                ('producer', models.CharField(default='Unknown', max_length=12)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
