# Generated by Django 6.0.3 on 2026-04-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
