# Generated by Django 6.0.3 on 2026-04-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex01', '0002_alter_movies_director_alter_movies_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='producer',
            field=models.CharField(max_length=128),
        ),
    ]
