# Generated by Django 6.0.4 on 2026-04-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0003_alter_people_created_alter_people_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='characters',
            field=models.ManyToManyField(related_name='movies', to='ex10.people'),
        ),
    ]
